### ISSUE TITLE
作者你好，请问你是如何实现定义跳转的，文件之间的那种

### ISSUE THREAD

**Issue by tornoda** [jaywcjlove/vim-web#6]
在网上查了很多资料都搞不清，请问前辈如何实现诸如import语句定义跳转的呢，还有类似node库的api自动提示不全呢（装了ycm似乎只能够提示js内建的语法提示）。

**Comment by jaywcjlove** [comment]
@tornoda 不好意思，我也没有找到这种插件

**Comment by tornoda** [comment]
> @tornoda 不好意思，我也没有找到这种插件

@jaywcjlove 我已经用上了，ycm支持微软的TSServer，安装的时候变成支持就可以了。如果觉得安装麻烦，可以直接使用coc.nvim，这个很简单，就是vim版本的vscode

**Comment by jaywcjlove** [comment]
@tornoda 👍 了解
