### ISSUE TITLE
vim

### ISSUE THREAD

**Issue by yesyestoday2020** [jaywcjlove/vim-web#8]
作者你好，对于已经写好的html文件，如何在vim中运行，查看代码运行结果

**Comment by jaywcjlove** [comment]
@heguohui2018 

1. 确认你安装了 vim
2. 打开命令行工具
3. 在命令行工具，进入你 HTML所在的目录 `cd ~/git`
4. 在命令行通过 vim 命令打开你的 HTML 文件 `vim ./index.html`

**Comment by yesyestoday2020** [comment]
谢谢，有没有实时编辑，浏览器自动更新预览的vim插件，
我暂时只想到通过映射一个快捷键，去调用外部的open命令，去打开html，去预览html,
是否有更好的方法。
